name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main # ou master, dependendo do nome da sua branch principal

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/formulaslim/
        # A pasta contém os arquivos HTML estáticos
        server-dir: ./
        # Substitua public_html/ pelo caminho correto se precisar, ex: public_html/seu-site.com/
